/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MagiaRouteImport } from './routes/magia'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ProyectosSlugRouteImport } from './routes/proyectos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MagiaRoute = MagiaRouteImport.update({
  id: '/magia',
  path: '/magia',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosSlugRoute = ProyectosSlugRouteImport.update({
  id: '/proyectos/$slug',
  path: '/proyectos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/magia': typeof MagiaRoute
  '/portfolio': typeof PortfolioRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/magia': typeof MagiaRoute
  '/portfolio': typeof PortfolioRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/magia': typeof MagiaRoute
  '/portfolio': typeof PortfolioRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/magia' | '/portfolio' | '/proyectos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/magia' | '/portfolio' | '/proyectos/$slug'
  id: '__root__' | '/' | '/magia' | '/portfolio' | '/proyectos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MagiaRoute: typeof MagiaRoute
  PortfolioRoute: typeof PortfolioRoute
  ProyectosSlugRoute: typeof ProyectosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magia': {
      id: '/magia'
      path: '/magia'
      fullPath: '/magia'
      preLoaderRoute: typeof MagiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/$slug': {
      id: '/proyectos/$slug'
      path: '/proyectos/$slug'
      fullPath: '/proyectos/$slug'
      preLoaderRoute: typeof ProyectosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MagiaRoute: MagiaRoute,
  PortfolioRoute: PortfolioRoute,
  ProyectosSlugRoute: ProyectosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
